### ISSUE TITLE
Unable to Install requirements file on windows?

### ISSUE THREAD

**Issue by JagadeeshwarReddy2001** [Gladiator07/Harvestify#19]
Hi, I'm unable to install requirements file on my windows system. Specs are Intel i5 processor, Intel Iris Xe graphics card, 16gb ram!
![Screenshot (36)](https://user-images.githubusercontent.com/68508818/224663613-3e9ed03c-8964-436c-8063-27e9ad50826b.png)

**Comment by azwinlam** [comment]
Doesn't the file say Linux? Torch
