### ISSUE TITLE
Throws Internal Server Error, If we put String values in Fields

### ISSUE THREAD

**Issue by Sumanshu-Nankana** [Gladiator07/Harvestify#4]
I would suggest to use 

input type="number" 
in HTML where only integers required

Instead of 

input type="text" 

Though you are converting into integer in predict function, but if anyone will enter string value example : 'abc' it will not convert into integer and application will throw Internal Server Error.

**Comment by Gladiator07** [comment]
Thanks for pointing out. This issue is fixed now .
