### ISSUE TITLE
Push rejected, failed to compile Python app.

### ISSUE THREAD

**Issue by bincynadar** [Gladiator07/Harvestify#5]
hey! I tried deploying your app with some changes in the Heroku app and it is showing me the following error
 ERROR: No matching distribution found for ipython==7.18.0 (from -r /tmp/build_e84c51fe/requirements.txt (line 22))
 !     Push rejected, failed to compile Python app.
 !     Push failed
any suggestions or help would be greatly appreciated. Thank you!

**Comment by Gladiator07** [comment]
Use the requirements.txt file from app folder. You can access it [here](https://github.com/Gladiator07/Harvestify/tree/master/app)
